### ISSUE TITLE
Wuttang chess engine

### ISSUE THREAD

**Issue by yellow-panther** [lokesh58/Wuttang#1]
Hello,
is your engine originally written from scratch or a derivative etc. from another chess program with open source? The ComputerChess Wiki http://computer-chess.org/doku.php?id=computer_chess:wiki:lists:chess_engine_list prefers to mention their authors with their full names.
I cannot detect under which license e.g. GNU 3 https://www.gnu.org/licenses/gpl-3.0.de.html Wuttang is published.

**Comment by lokesh58** [comment]
It's built from scratch. This was just for fun so I didn't licensed it.
